### ISSUE TITLE
Just Noise after use

### ISSUE THREAD

**Issue by Alijaaan** [timkellypa/wave_builder#3]
Hi dears,

I tried to use the plugin, seems great , but no luck yet.
I recorded my audio from flutter_webrtc and saved my data in a Unit8List data temporary.
I can play it and its ok.
My problem is I need to add header to my file before upload to be able manage better playing like slider and ...
I used the plugin with no errors but when I play back the file just I have noise.

any lead or help would be appreciated.

**Comment by timkellypa** [comment]
Hello,

Really sorry for the extremely late response.  I haven't really been monitoring this module.

Basically, if you use the constructor with no params, it will assume the files you append have these attributes (bit rate, frequency, and stereo):

`WaveBuilder({int bitRate = 16, int frequency = 44100, bool stereo = true})`

Please double check that.  If yours are different, you can override them in the constructor.

If you're still having issues, please try first by using the wav files in the sample project:
`example/assets/wav/primary.wav`, for instance.  If that one works, it likely has to do with your file format being different somehow.

This is just for anyone encountering the same issue, and not just @Alijaaan, since I'm unfortunately probably 3 years late to solve your problem, and again, I'm very sorry about that.

I'll close this issue, since I assume it's a format problem, but if it is still an issue for you or anyone else, please reopen it with a sample file, and I'll take a look.

Thanks,
Tim
